export const IPC_CHANNELS = {
  IMAGE_GENERATE: 'image:generate',
  IMAGE_GENERATE_PROGRESS: 'image:generate-progress',
  IMAGE_GENERATE_CANCEL: 'image:generate-cancel',
  IMAGE_SAVE: 'image:save',
  IMAGE_EXPORT: 'image:export',
  IMAGE_START_DRAG: 'image:start-drag',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  HISTORY_LOAD: 'history:load',
  HISTORY_SAVE: 'history:save',
  HISTORY_DELETE: 'history:delete',
  HISTORY_LIST: 'history:list',
  IMAGE_READ: 'image:read',
  IMAGE_DELETE: 'image:delete',
  MIGRATE_RUN: 'migrate:run',
  IMAGE_UPLOAD_URLS: 'image:upload-urls',
  VIDEO_GENERATE: 'video:generate',
  VIDEO_GENERATE_PROGRESS: 'video:generate-progress',
  VIDEO_EXPORT: 'video:export',
  UPDATE_CHECK: 'update:check',
  UPDATE_DOWNLOAD: 'update:download',
  UPDATE_INSTALL: 'update:install',
  UPDATE_STATUS: 'update:status',
  UPDATE_REVEAL: 'update:reveal',
} as const

export const MAX_IMAGE_COUNT = 4
